// AUTO-GENERATED by scripts/extract-gallery-exif.mjs — do not edit by hand.
// Run `npm run gallery:scan` after adding or removing files from
// static/images/gallery/ to regenerate this manifest.

export interface GeneratedGalleryItem {
	src: string;
	alt: string;
	date?: string;
	aspect?: number;
}

export const generatedGallery: GeneratedGalleryItem[] = [];
