// AUTO-GENERATED by scripts/extract-gallery-exif.mjs — do not edit by hand.
// Run `npm run gallery:scan` after adding or removing files from
// static/images/gallery/ to regenerate this manifest.

export interface GeneratedGalleryItem {
	src: string;
	alt: string;
	date?: string;
	aspect?: number;
}

export const generatedGallery: GeneratedGalleryItem[] = [
	{
		"src": "/images/gallery/dsc09889.jpg",
		"alt": "Dsc09889",
		"date": "2025-12-30T04:46:27.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09882.jpg",
		"alt": "Dsc09882",
		"date": "2025-12-30T04:45:43.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09867.jpg",
		"alt": "Dsc09867",
		"date": "2025-12-30T04:43:00.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09750.jpg",
		"alt": "Dsc09750",
		"date": "2025-12-28T08:21:31.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09735.jpg",
		"alt": "Dsc09735",
		"date": "2025-12-28T07:05:30.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09731.jpg",
		"alt": "Dsc09731",
		"date": "2025-12-28T06:48:26.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09726.jpg",
		"alt": "Dsc09726",
		"date": "2025-12-28T06:44:11.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09721.jpg",
		"alt": "Dsc09721",
		"date": "2025-12-28T06:39:12.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09706.jpg",
		"alt": "Dsc09706",
		"date": "2025-12-28T04:40:54.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09691.jpg",
		"alt": "Dsc09691",
		"date": "2025-12-28T04:35:47.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09690.jpg",
		"alt": "Dsc09690",
		"date": "2025-12-28T04:33:27.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09669.jpg",
		"alt": "Dsc09669",
		"date": "2025-12-28T04:19:05.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09661.jpg",
		"alt": "Dsc09661",
		"date": "2025-12-28T04:16:21.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09659.jpg",
		"alt": "Dsc09659",
		"date": "2025-12-28T04:15:35.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09654.jpg",
		"alt": "Dsc09654",
		"date": "2025-12-28T04:14:50.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09640.jpg",
		"alt": "Dsc09640",
		"date": "2025-12-28T04:05:52.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09612.jpg",
		"alt": "Dsc09612",
		"date": "2025-12-24T09:57:28.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09547.jpg",
		"alt": "Dsc09547",
		"date": "2025-12-18T08:40:31.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09542.jpg",
		"alt": "Dsc09542",
		"date": "2025-12-18T08:39:40.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09531.jpg",
		"alt": "Dsc09531",
		"date": "2025-12-18T08:36:03.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09520.jpg",
		"alt": "Dsc09520",
		"date": "2025-12-18T08:32:48.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09514.jpg",
		"alt": "Dsc09514",
		"date": "2025-12-18T08:31:19.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09497.jpg",
		"alt": "Dsc09497",
		"date": "2025-12-18T08:21:44.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09495.jpg",
		"alt": "Dsc09495",
		"date": "2025-12-18T08:21:24.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09487.jpg",
		"alt": "Dsc09487",
		"date": "2025-12-18T08:19:52.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09485.jpg",
		"alt": "Dsc09485",
		"date": "2025-12-18T08:19:34.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09470.jpg",
		"alt": "Dsc09470",
		"date": "2025-12-18T07:39:13.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09465.jpg",
		"alt": "Dsc09465",
		"date": "2025-12-18T07:38:25.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09395.jpg",
		"alt": "Dsc09395",
		"date": "2025-12-18T07:12:47.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09369.jpg",
		"alt": "Dsc09369",
		"date": "2025-12-18T07:06:11.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09297.jpg",
		"alt": "Dsc09297",
		"date": "2025-12-18T06:43:41.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09288.jpg",
		"alt": "Dsc09288",
		"date": "2025-12-18T06:41:24.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09199.jpg",
		"alt": "Dsc09199",
		"date": "2025-12-18T06:11:53.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09167.jpg",
		"alt": "Dsc09167",
		"date": "2025-12-18T05:48:40.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09161.jpg",
		"alt": "Dsc09161",
		"date": "2025-12-18T05:47:37.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09121.jpg",
		"alt": "Dsc09121",
		"date": "2025-12-18T04:25:51.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09113.jpg",
		"alt": "Dsc09113",
		"date": "2025-12-18T04:24:10.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09087.jpg",
		"alt": "Dsc09087",
		"date": "2025-12-18T03:28:36.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09080.jpg",
		"alt": "Dsc09080",
		"date": "2025-12-18T03:26:47.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09078.jpg",
		"alt": "Dsc09078",
		"date": "2025-12-18T03:26:39.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09075.jpg",
		"alt": "Dsc09075",
		"date": "2025-12-18T03:25:22.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09057.jpg",
		"alt": "Dsc09057",
		"date": "2025-12-18T03:16:56.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/img_5756.jpg",
		"alt": "Img 5756",
		"date": "2025-12-14T16:29:00.000Z",
		"aspect": 0.75
	},
	{
		"src": "/images/gallery/dsc04353.jpg",
		"alt": "Dsc04353",
		"date": "2025-11-14T05:04:34.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc04352.jpg",
		"alt": "Dsc04352",
		"date": "2025-11-14T05:04:06.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc04350.jpg",
		"alt": "Dsc04350",
		"date": "2025-11-14T05:03:53.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc04348.jpg",
		"alt": "Dsc04348",
		"date": "2025-11-14T05:00:58.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/img_5612.jpg",
		"alt": "Img 5612",
		"date": "2025-10-26T12:24:59.000Z",
		"aspect": 0.75
	},
	{
		"src": "/images/gallery/img_1233.jpg",
		"alt": "Img 1233",
		"date": "2025-10-18T02:53:20.000Z",
		"aspect": 0.75
	},
	{
		"src": "/images/gallery/dsc04110.jpg",
		"alt": "Dsc04110",
		"date": "2025-09-27T16:30:50.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc04104.jpg",
		"alt": "Dsc04104",
		"date": "2025-09-27T16:18:15.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc04096.jpg",
		"alt": "Dsc04096",
		"date": "2025-09-27T16:07:46.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc04083.jpg",
		"alt": "Dsc04083",
		"date": "2025-09-27T16:02:46.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc04038.jpg",
		"alt": "Dsc04038",
		"date": "2025-09-27T15:25:57.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc04036.jpg",
		"alt": "Dsc04036",
		"date": "2025-09-27T15:25:03.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc04024.jpg",
		"alt": "Dsc04024",
		"date": "2025-09-27T15:18:31.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc04014.jpg",
		"alt": "Dsc04014",
		"date": "2025-09-27T15:14:17.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc04004.jpg",
		"alt": "Dsc04004",
		"date": "2025-09-27T15:10:11.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc04001.jpg",
		"alt": "Dsc04001",
		"date": "2025-09-27T15:04:58.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03999.jpg",
		"alt": "Dsc03999",
		"date": "2025-09-20T19:16:09.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03802.jpg",
		"alt": "Dsc03802",
		"date": "2025-09-20T17:26:14.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03703.jpg",
		"alt": "Dsc03703",
		"date": "2025-09-20T16:17:51.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03579.jpg",
		"alt": "Dsc03579",
		"date": "2025-09-20T15:06:25.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03535.jpg",
		"alt": "Dsc03535",
		"date": "2025-09-20T14:39:37.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc03501.jpg",
		"alt": "Dsc03501",
		"date": "2025-09-07T02:13:23.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03500.jpg",
		"alt": "Dsc03500",
		"date": "2025-09-07T02:12:34.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc03405.jpg",
		"alt": "Dsc03405",
		"date": "2025-09-07T01:36:52.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03398.jpg",
		"alt": "Dsc03398",
		"date": "2025-09-07T01:35:32.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03377.jpg",
		"alt": "Dsc03377",
		"date": "2025-09-07T01:26:36.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03323.jpg",
		"alt": "Dsc03323",
		"date": "2025-09-07T01:06:53.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc03321.jpg",
		"alt": "Dsc03321",
		"date": "2025-09-07T01:06:34.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03319.jpg",
		"alt": "Dsc03319",
		"date": "2025-09-07T01:05:59.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03286.jpg",
		"alt": "Dsc03286",
		"date": "2025-08-24T19:40:41.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03272.jpg",
		"alt": "Dsc03272",
		"date": "2025-08-24T19:34:33.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc03262.jpg",
		"alt": "Dsc03262",
		"date": "2025-08-24T19:31:21.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc03126.jpg",
		"alt": "Dsc03126",
		"date": "2025-08-24T15:53:54.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc02880.jpg",
		"alt": "Dsc02880",
		"date": "2025-08-24T13:29:32.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc02879.jpg",
		"alt": "Dsc02879",
		"date": "2025-08-24T13:29:22.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc02874.jpg",
		"alt": "Dsc02874",
		"date": "2025-05-04T18:38:25.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc02790.jpg",
		"alt": "Dsc02790",
		"date": "2025-05-04T17:12:11.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc02345.jpg",
		"alt": "Dsc02345",
		"date": "2025-04-26T16:52:08.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc02286.jpg",
		"alt": "Dsc02286",
		"date": "2025-04-26T16:29:21.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc02279.jpg",
		"alt": "Dsc02279",
		"date": "2025-04-26T16:27:25.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc02233.jpg",
		"alt": "Dsc02233",
		"date": "2025-04-26T16:15:07.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc02119.jpg",
		"alt": "Dsc02119",
		"date": "2024-10-05T19:58:01.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc02048.jpg",
		"alt": "Dsc02048",
		"date": "2024-10-05T19:24:48.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc01978.jpg",
		"alt": "Dsc01978",
		"date": "2024-10-05T19:01:32.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc01900.jpg",
		"alt": "Dsc01900",
		"date": "2024-10-05T18:35:10.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc01872.jpg",
		"alt": "Dsc01872",
		"date": "2024-10-05T18:22:09.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc01625.jpg",
		"alt": "Dsc01625",
		"date": "2024-09-28T17:34:40.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc01569.jpg",
		"alt": "Dsc01569",
		"date": "2024-09-28T17:25:30.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc01551.jpg",
		"alt": "Dsc01551",
		"date": "2024-09-28T17:20:16.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc01487.jpg",
		"alt": "Dsc01487",
		"date": "2024-09-28T16:59:29.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc01482.jpg",
		"alt": "Dsc01482",
		"date": "2024-09-28T16:54:59.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc01479.jpg",
		"alt": "Dsc01479",
		"date": "2024-09-28T16:54:18.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc01453.jpg",
		"alt": "Dsc01453",
		"date": "2024-09-28T16:42:00.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc00044.jpg",
		"alt": "Dsc00044",
		"date": "2024-08-11T17:12:55.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09959.jpg",
		"alt": "Dsc09959",
		"date": "2024-08-11T16:49:06.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09939.jpg",
		"alt": "Dsc09939",
		"date": "2024-08-11T16:41:29.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc01140.jpg",
		"alt": "Dsc01140",
		"date": "2024-04-27T20:00:54.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc01005.jpg",
		"alt": "Dsc01005",
		"date": "2024-04-27T19:37:22.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc00612.jpg",
		"alt": "Dsc00612",
		"date": "2024-04-27T17:56:44.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc00603.jpg",
		"alt": "Dsc00603",
		"date": "2024-04-27T17:51:46.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc00395.jpg",
		"alt": "Dsc00395",
		"date": "2024-04-27T16:57:32.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc00361.jpg",
		"alt": "Dsc00361",
		"date": "2024-04-27T16:50:40.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc00032.jpg",
		"alt": "Dsc00032",
		"date": "2023-12-29T00:33:07.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc00011.jpg",
		"alt": "Dsc00011",
		"date": "2023-12-29T00:24:57.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc00009.jpg",
		"alt": "Dsc00009",
		"date": "2023-12-29T00:24:51.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc00007.jpg",
		"alt": "Dsc00007",
		"date": "2023-12-29T00:24:26.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc09952.jpg",
		"alt": "Dsc09952",
		"date": "2023-12-29T00:02:08.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc00647.jpg",
		"alt": "Dsc00647",
		"date": "2023-08-27T19:19:41.000Z",
		"aspect": 1.5004
	},
	{
		"src": "/images/gallery/dsc00431.jpg",
		"alt": "Dsc00431",
		"date": "2023-08-27T18:07:42.000Z",
		"aspect": 1.2808
	},
	{
		"src": "/images/gallery/dsc00403.jpg",
		"alt": "Dsc00403",
		"date": "2023-08-27T18:05:54.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09910.jpg",
		"alt": "Dsc09910",
		"date": "2023-08-19T06:14:50.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc09793.jpg",
		"alt": "Dsc09793",
		"date": "2023-08-19T05:08:10.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc03294.jpg",
		"alt": "Dsc03294",
		"date": "2023-06-11T04:53:49.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/dsc02990.jpg",
		"alt": "Dsc02990",
		"date": "2023-06-03T17:25:17.000Z",
		"aspect": 0.6665
	},
	{
		"src": "/images/gallery/img_9325_jpg.jpg",
		"alt": "Img 9325 Jpg",
		"date": "2022-06-23T15:04:39.000Z",
		"aspect": 1.3333
	},
	{
		"src": "/images/gallery/img_9159_jpg.jpg",
		"alt": "Img 9159 Jpg",
		"date": "2022-06-19T01:04:33.000Z",
		"aspect": 1.1838
	},
	{
		"src": "/images/gallery/img_9127_jpg.jpg",
		"alt": "Img 9127 Jpg",
		"date": "2022-06-18T16:44:21.000Z",
		"aspect": 1.3333
	}
];
